version: "3.8"

services:
    app:
        ports:
            - "${APP_PORT}:80"
        build: ./docker/app
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - network
        restart: always
    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_ROOT_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "3306:3306"
        networks:
            - network
    adminer:
        image: adminer
        restart: always
        ports:
            - "${APP_ADMINER}:8080"
        networks:
            - network
networks:
    network:
        driver: bridge
